development: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: leave_management_system_dev
  pool: 5
  username: postgres
  password: root
  host: localhost

test: &test
  <<: *default
  database: test_leave

production: &production
  <<: *default
  database: prod_leave